name: Storage Intializer Docker Publisher using IBM Cloud

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - test2

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: storage-initializer
  IMAGE_REGISTRY: quay.io
  IMAGE_ORG: r3hankhan
  QUAYIO_USERNAME: r3hankhan
  QUAYIO_PASSWORD: FI58faza0po36UOtaHKgc1TFV++AMq5GUVT36m2m5y+MGlwOC+fwxGjwdOZCM8sWgphX7anNhlbkAj+TDTKU9A==
  VERSION: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup SSH config for builders
        env:
          BUILDER_S390X_SSH_HOST: 165.192.139.9
          BUILDER_S390X_SSH_KEY: ${{ secrets.BUILDER_S390X_SSH_KEY }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh

          touch ~/.ssh/id_builder_s390x
          chmod 600 ~/.ssh/id_builder_s390x
          echo "$BUILDER_S390X_SSH_KEY" > ~/.ssh/id_builder_s390x

          touch ~/.ssh/config
          chmod 600 ~/.ssh/config
          cat >~/.ssh/config <<END
          Host builder-s390x
            StrictHostKeyChecking no
            HostName $BUILDER_S390X_SSH_HOST
            User root
            IdentityFile "~/.ssh/id_builder_s390x"
          END
          cat ~/.ssh/config
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
          append: |
            - endpoint: ssh://builder-s390x
              platforms: linux/s390x

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ env.QUAYIO_USERNAME }}
          password: ${{ env.QUAYIO_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/s390x
          context: python
          file: python/storage-initializer.Dockerfile
          push: true
          tags: quay.io/r3hankhan/storage-initializer:latest
          provenance: false
      
